apiVersion: v1
kind: Service
metadata:
  annotations:
  name: datagrid-service-xsite
spec:
  clusterIP: 172.30.244.221
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32660
    port: 8660
    protocol: TCP
    targetPort: 8660
  selector:
    deploymentConfig: datagrid-service-xsite-hello-world
  sessionAffinity: None
  type: NodePort
