apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  name: pv-dg-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: srv-data-datagrid-service-xsite-hello-world-0
    namespace: datagrid-site-sul
  nfs:
    path: /dados/datagrid-service-0
    server: 10.0.90.193
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
