apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  name: pv-dg-2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: srv-data-datagrid-service-xsite-hello-world-2
    namespace: datagrid-site-sul
  nfs:
    path: /dados/datagrid-service-2
    server: 10.74.176.237
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
