apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  name: pv-dg-configuration
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datagrid-configuration
    namespace: datagrid-site-sul
  nfs:
    path: /dados/datagrid-configuration
    server: 10.74.176.237
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
