apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: datagrid-configuration
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: pv-dg-configuration
