apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: srv-data-datagrid-service-xsite-hello-world-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: pv-dg-1
